### ISSUE TITLE
Updating to bedmachine landfrac

### ISSUE THREAD

**Issue by PeterHjortLauritzen** [NCAR/Topo#40]
Rene Wijngaard has updated our MODIS land fraction dataset to  GrIS and AIS high resolution bedmachine data over Greenland and Antartica. The difference between updated dataset and GMTED2010 is here:

![Screen Shot 2022-05-19 at 3 25 28 PM](https://user-images.githubusercontent.com/8782989/169407234-94c5a8b9-6803-43ce-aee2-f7568e452119.png)

**Comment by adamrher** [comment]
It seems the MODIS dataset considered the Arctic ice shelves as ocean. This is technically correct (the ice shelves are floating on top of the ocean ... like sea ice). Rene purposefully considered ice shelves as land because for our purposes, it is better that we not zero out the ice shelves, since they are a 100 meters or so above ocean surface.

**Comment by JulioTBacmeister** [comment]
So what have we decided to do?  If they are permanent year round features
at 100m elevation it may be OK to treat them as land. I think the
physically significant change we are after is reducing temperature biases
over rapidly flowing coastal currents.

**Comment by adamrher** [comment]
(corrected above post because I incorrectly referred to Arctic instead of Antarctic ice shelves). Those big Ross and Ronnie  ice shelves are perennial. We should consider them land in our topo software, since we don't want to zero out elevations over ice shelves. So this new merged BM+MODIS landfrac product is a better dataset.

**Comment by JulioTBacmeister** [comment]
Sorry for a naive question - but why is there so much structure over land?

**Comment by PeterHjortLauritzen** [comment]
Here is screenshot of raw ~1km data:

<img width="1063" alt="Screen Shot 2022-05-20 at 10 48 06 AM" src="https://user-images.githubusercontent.com/8782989/169574967-59548f1f-36d6-4f45-82b2-7d2b7dfa96d0.png">
